### ISSUE TITLE
Error in PostScriptTrace(p1, p2) : sorry, 'gs' cannot be found

### ISSUE THREAD

**Issue by amjass12** [jianhaizhang/spatialHeatmap#1]
Hi!

thank you for this tool! when running the vignette and example code: 

`shm.lis <- spatial_hm(svg.path=svg.hum, data=my_vec, ID='toy', ncol=1, height=0.9, width=0.8, sub.title.size=20, legend.nrow=2, ft.trans=c('g4320'))
`
i get the error (in title) - this isn't really intuitive and not sure where it is coming from. any help is much appreciated! 

thank you :)

**Comment by jianhaizhang** [comment]
Hello,

Thanks for using spatialHeatmap.
I guess you are using the Windows system. Make sure you installed `gs` under `C:/gs/gs9.20/bin/gswin32c.exe` and run `Sys.setenv(R_GSCMD = normalizePath("C:/gs/gs9.20/bin/gswin32c.exe")) ` in R. Let me know if you still have errors.
Here is a reference: https://stackoverflow.com/questions/35256501/windows-rgrimport-ghostscript-error-status-127

Regards

**Comment by jianhaizhang** [comment]
I am closing this issue. If you have more errors, feel free to report them.
