### ISSUE TITLE
Mouse coronal svg-Not an issue more about a function 

### ISSUE THREAD

**Issue by MusculusMus** [jianhaizhang/spatialHeatmap#3]
hi,

Beautiful package to show spatial data as a heatmap. After I quick read your vignettes, I find only the sagittal mouse brain available, are you going to include the coronal mouse brain atlas as well?

For the regions included,  It is more valuable to separate the large regions into smaller ones, for example, split the cerebral cortex into the olfactory area, somatosensory area, and auditory cortex...

[5] "medulla.oblongata"            "cerebral.cortex"             
[7] "corpus.striatum"              "diencephalon"                
[9] "pituitary.gland"              "hippocampus"                 
[11] "cerebellum"                   "brainstem"                   
[13] "midbrain"                     "dorsal.plus.ventral.thalamus"
[15] "hypothalamus"                 "nose"                        
[17] "corpora.quadrigemina"

Best,
Shuai

**Comment by jianhaizhang** [comment]
Hello Shuai,

Thanks for your suggestion. Currently, a limited number of aSVG instances are ready to use at https://github.com/ebi-gene-expression-group/anatomogram/tree/master/src/svg or https://github.com/jianhaizhang/spatialHeatmap_aSVG_Repository. In the long-term, we aim to include more instances for the most widely used species, including the sagittal mouse brain. 

However, one can always create custom aSVG images according to our step-by-step tutorial https://jianhaizhang.github.io/SVG_tutorial_file/

Regards,
Jianhai

**Comment by MusculusMus** [comment]
Hi Jianhai,

Thanks for your sharing and it’s a good instruction to create custom aSVG.

I will follow this Tutorial to create a coronal adult mouse brain SHM svg. If it works, I will share my image with you.

Thanks again.

Best,
Shuai

From: Jianhai Zhang ***@***.***>
Date: Tuesday, August 30, 2022 at 21:42
To: jianhaizhang/spatialHeatmap ***@***.***>
Cc: Shuai Wang ***@***.***>, Author ***@***.***>
Subject: Re: [jianhaizhang/spatialHeatmap] Mouse coronal svg-Not an issue more about a function (Issue #3)

Hello Shuai,

Thanks for your suggestion. Currently, a limited number of aSVG instances are ready to use at https://github.com/ebi-gene-expression-group/anatomogram/tree/master/src/svg or https://github.com/jianhaizhang/spatialHeatmap_aSVG_Repository. In the long-term, we aim to include more instances for the most widely used species, including the sagittal mouse brain.

However, one can always create custom aSVG images according to our step-by-step tutorial https://jianhaizhang.github.io/SVG_tutorial_file/

Regards,
Jianhai

**Comment by MusculusMus** [comment]
Hi Jianhai,

Great news to share with you, I followed the step-by-step tutorial and finally have a plot.

Thanks a lot for your package. Is it possible to move the color legend somewhere else? On the right with region legend is better in my case, but I cannot find a parameter to change it.



Best,
Shuai


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jianhaizhang** [comment]
Hi Shuai,

The `legend.2nd` (TRUE or FALSE) and `legend.plot` (all or NULL) can be used to customize the legends.

Regards,
Jianhai

**Comment by jianhaizhang** [comment]
I am closing this issue. Feel free to contact me if you have more questions.
