### ISSUE TITLE
Issue with read_svg and img_na_pa

### ISSUE THREAD

**Issue by conchasan** [jianhaizhang/spatialHeatmap#4]
Hi there! 

I am attempting to run through some of the example spatial heatmaps that utilize the vector and data.frame classes, but I keep running into an error where R does not find the img_pa_na function required of read_svg. I suspect it is a package/dependency issue since I couldn't find the problematic img_pa_na() function in any of the github code. Could you shed some light on how I can correct this issue?

Thanks,
Andrew

**Comment by jianhaizhang** [comment]
Hi Andrew,

Thanks for using spatialHeatmap. Can you share your code? And which version are you using?

Regards,
Jianhai

**Comment by conchasan** [comment]
> Hi Andrew,
> 
> Thanks for using spatialHeatmap. Can you share your code? And which version are you using?
> 
> Regards, Jianhai

No problem, the package has some exciting potential. You asking what version I was using prompted me to update to the latest release github release (2.5.3) instead of the version in bioconductor (2.2.0) and now the function works as intended.

I was attempting to use the read_svg function to check the formatting a custom created SVG to ensure that the absolute positions of the tissue would be read in correctly. It turns out I still need to fix some issues with the SVG, but the original issue has been solved. Thanks!

**Comment by jianhaizhang** [comment]
Thanks for the feedback!

**Comment by jianhaizhang** [comment]
Thanks for the feedback!
