### ISSUE TITLE
Issue with spatial_hm 

### ISSUE THREAD

**Issue by ghost** [jianhaizhang/spatialHeatmap#5]
Hi. 

Nice package. So trying that it works out, however I keep running into the error with spatial_hm. 

The svg is read fine without any error. The 'return_feature' function lists out the features perfectly. The data is also formatted as stated - gene names as rownames of the dataframe and the cell types (one word only) as colnames. The name of svg feature and id are same as the colnames of data frame (expression_data). But with spatial_hm following error returns.

`shm.lis <- spatial_hm(svg.path= svg.hum1, data=expression_data, ID='Gene1', ncol=1, height=0.9, width=0.8, sub.title.size=20, legend.nrow=2)`

Error in strsplit(path.na, "/") : non-character argument

Can you suggest what might be the issue. 
Many thanks,
Eshan

**Comment by jianhaizhang** [comment]
Hello Eshan,

The "spatial_hm" function will be be deprecated. Please use the "shm" as explained in the vignette:
https://www.bioconductor.org/packages/release/bioc/vignettes/spatialHeatmap/inst/doc/spatialHeatmap.html#3_Spatial_Heatmaps

Regards,
Jianhai

**Comment by jianhaizhang** [comment]
I am closing this issue and feel free to let me know if you have more issues.

**Comment by jianhaizhang** [comment]
I am closing this issue and feel free to let me know if you have more issues.
